version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app:delegated
    networks:
      - hearteye-network
    restart: unless-stopped

networks:
  hearteye-network:
    driver: bridge